### ISSUE TITLE
DummyImageSource doesn't work with libvips

### ISSUE THREAD

**Issue by Sebobo** [sitegeist/Sitegeist.Kaleidoscope#7]
Using vips as image processor causes exceptions as it doesn't yet support the draw method used by the `DummyImageSource` to generate images on the fly.

I solved the problem in one project by using another FLOW_CONTEXT when the controller is called and overriding the image library via the sub context. But this is a bit advanced and not a great solution.

There should be a way to have a fallback or at least catch the error and give a hint about what's going on.

**Comment by mficzel** [comment]
@Sebobo Not sure what we can do here. What does the dummy image controller return instead of the image I would expect an error message instead of the image plus some meaningful info in the logs. 

I understand that its will be hard to spot as the browsers will include the dummyimage as a src and thus the error is hard to spot. But i am not sure how to circumvent this.

I did not reproduce the error since i have no vips at hand If no status 500 is returned i would consider it a bug and work in this.

**Comment by Sebobo** [comment]
How about catching the exception and return the link to a static image/svg that contains some "rendering error" text?

Then it's immediately visible what's going on, and maybe we could even make it configurable.

**Comment by jonnitto** [comment]
@mficzel A configuration for vips looks like this:

```yaml
Neos:
  Imagine:
    driver: 'Vips'
    enabledDrivers:
      Vips: true
      Gd: true
      Imagick: true
  Media:
    image:
      defaultOptions:
        # The Vips driver does not support interlace
        interlace: ~
```

Perhaps it could solve the problem to check if the driver is Vips and get the enabled Drivers (In this case `Imagick`) and use this library. Would this be a way to go?
